config/routes.rb
Rails.application.routes.draw do

  resources :tasks
  devise_for :users

  root 'pages#home'

  get 'about' => "pages#about"
  get 'test'  => "pages#test"

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def test
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  # GET /tasks
  # GET /tasks.json
def index
  @to_do = current_user.tasks.where(state: "to_do")
  @doing = current_user.tasks.where(state: "doing")
  @done = current_user.tasks.where(state: "done")
  respond_with(@tasks)
end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    respond_with(@task)
  end

  # GET /tasks/new
  def new
    @task = Task.new
    respond_with(@task)
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
def create
  @task = current_user.tasks.new(task_params)
  @task.save
  respond_with(@task)
end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
   @task.update(task_params)
   respond_with(@task)
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<i class='fa fa-circle-o-notch'></i> Stukdo".html_safe, root_path, class: "navbar-brand" 
      %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
        <li><%= link_to "About", about_path %></li>
        <li> <%= link_to "Login", new_user_session_path %></li>
       <% end %>        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stukdo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>	
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Our vision is to improve people's productivity</p>

app/views/pages/home.html.erb
<h1>Hello World. My name is Giulia</h1>

<div class="jumbotron">
<h1><i class="fa fa-circle-o-notch"></i> Stukdo</h1>
<p>This is my smart to do list Ruby on Rails Application</p>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/pages/test.html.erb
<div class="row">
	<div class="col-md-4 text-center"><h1 class="text-center">To-do</h1>

		<div class="panel panel-info">
		<div class="panel-heading">Heading</div>
		<div class="panel-body">Content</div>
		<div class="panel-footer text-center">Footer</div>
		</div>		

	</div>
	<div class="col-md-4"><h1 class="text-center">Doing</h1></div>
	<div class="col-md-4"><h1 class="text-center">Done</h1></div>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :state %>
    <%= f.input :text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>To do</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @to_do.each do |task| %>
      <tr>
        <td><%= task.content %></td>
        <td><%= task.state %></td>
        <td><%= task.text %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>Doing</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doing.each do |task| %>
      <tr>
        <td><%= task.content %></td>
        <td><%= task.state %></td>
        <td><%= task.text %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>Done</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @done.each do |task| %>
      <tr>
        <td><%= task.content %></td>
        <td><%= task.state %></td>
        <td><%= task.text %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>State:</strong>
  <%= @task.state %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>